# Generated by Django 4.2.1 on 2023-05-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='horario',
            field=models.TimeField(default='16:00:00'),
        ),
    ]
