# Generated by Django 4.2.1 on 2023-06-10 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_remedio_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remedio',
            name='horario',
            field=models.TimeField(default='16:00'),
        ),
    ]
